name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the baseImage
      - name: Build and Push baseImage
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project-central-dump-baseimage:latest ./baseImage
          docker push ${{ secrets.DOCKER_USERNAME }}/project-central-dump-baseimage:latest

      # Step 4: Build and push the control image
      - name: Build and Push control
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project-central-dump-control:latest ./control
          docker push ${{ secrets.DOCKER_USERNAME }}/project-central-dump-control:latest

      # Step 5: Build and push the monitoring image
      - name: Build and Push monitoring
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project-central-dump-monitoring:latest ./monitoring
          docker push ${{ secrets.DOCKER_USERNAME }}/project-central-dump-monitoring:latest